# This workflow will do a clean install of node dependencies, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Clean Install
      run: npm ci
    - name: Check
      env:
        BRANCH_NAME: ${{ replace(github.head_ref, "refs/heads/", "") }}
      run: npm run check --if-present
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm test --if-present
